#NOTES

# to run the container
# docker compose up -d
# -d means detach

# see running container
# docker compose ps
# docker ps
# docker container ls

# to enter inside container terminal / bash into the container
# docker exec -it postgres bash
# postgres is the container name
# -it means Interactive Mode

# to quit from container bash / terminal
# ctrl + d

# to enter inside postgres terminal / psql (the interactive shell client of postgresql)
# psql -U farrel
# farrel is the username of the postgres

# to quit from psql
# \q

# to list databases
# \l

# to connect to a database
# \c database_name

# to list the tables
# \dt

# to see the connection pool
# SELECT * FROM pg_stat_activity;
# before press enter, we can press ctrl + c and type \x to expand display

# ctrl + l
# clear the psql screen

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: farrel
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#    depends_on:
#      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
#  pgadmin: