server:
#  port: 3030 # default 8080
  port: 8080 # default 8080
  error:
    include-message: always

spring:
  main:
#    web-application-type: none #default servlet
    web-application-type: servlet #default servlet